version: "3"

services:
  sample:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
      # - "/etc/letsencrypt/:/etc/letsencrypt/"
      # - "/etc/ssl/:/etc/ssl/"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    # container_name: mongo
    # build:
    #   context: .
    #   dockerfile: Dockerfile_2
    # volumes:
    #   - ".:/app/server"
    #   - "/app/node_modules"
    ports:
      - "17017:27017"
    # environment:
    #   - NODE_ENV=development
    # restart: always

  sample_2:
    container_name: portfolio_2
    build:
      context: .
      dockerfile: Dockerfile_2
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    restart: always




    